CREATE TABLE STATS (
   STAT_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
   STAT_DATE DATETIME NOT NULL,
   STAT VARCHAR(20) NOT NULL,
   VALUE INT(11) NOT NULL
);

CREATE VIEW BESTSELLERS_COUNT AS SELECT COUNT(*) 'Bestseller count' FROM books WHERE BESTSELLER = TRUE;

USE KODILLA_COURSE;
DELIMITER |
CREATE EVENT UPDATE_BESTSELLERS ON SCHEDULE EVERY 2 MINUTE DO
    BEGIN
        DECLARE best BOOLEAN;
        CALL UpdateBestsellers();
        SELECT COUNT(*) FROM books WHERE BESTSELLER = TRUE INTO best;
        INSERT INTO stats (STAT_DATE, STAT, VALUE) VALUES (CURTIME(), 'BESTSELLERS', best);
    END|
DELIMITER ;